In [2]:
import numpy as np

In [5]:
x = np.array([1,2,3,4], dtype=np.int64)

In [6]:
x.dtype

dtype('int64')

In [7]:
x.shape

(4,)

In [9]:
matrix = np.array([[2, 3, 4], [5, 6, 7]])

In [10]:
matrix.shape

(2, 3)

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.zeros(2)

array([0., 0.])

In [13]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [14]:
np.random.random((2, 3))

array([[0.41662939, 0.30357296, 0.71309682],
       [0.47307363, 0.57531699, 0.38867956]])

In [15]:
x[1]

2

In [20]:
matrix = np.array([[1,3,4,7], [2,5,9,8]])

In [21]:
matrix

array([[1, 3, 4, 7],
       [2, 5, 9, 8]])

In [29]:
matrix[0, 2]

4

In [30]:
matrix[:, :3]

array([[1, 3, 4],
       [2, 5, 9]])

In [31]:
matrix > 2

array([[False,  True,  True,  True],
       [False,  True,  True,  True]])

In [32]:
matrix[matrix > 2]

array([3, 4, 7, 5, 9, 8])

In [33]:
matrix.shape

(2, 4)

In [34]:
matrix.flatten()

array([1, 3, 4, 7, 2, 5, 9, 8])

In [35]:
matrix.T

array([[1, 2],
       [3, 5],
       [4, 9],
       [7, 8]])

In [37]:
matrix.reshape((8, 1))

array([[1],
       [3],
       [4],
       [7],
       [2],
       [5],
       [9],
       [8]])

In [38]:
matrix.reshape((1, 8))

array([[1, 3, 4, 7, 2, 5, 9, 8]])

In [39]:
matrix.resize((8, 1))

In [40]:
matrix

array([[1],
       [3],
       [4],
       [7],
       [2],
       [5],
       [9],
       [8]])

In [41]:
v = np.array([9,10])
w = np.array([11, 12])

In [42]:
v + w

array([20, 22])

In [43]:
np.add(v, w)

array([20, 22])

In [44]:
v - w

array([-2, -2])

In [45]:
np.subtract(v, w)

array([-2, -2])

In [46]:
np.multiply(v, w)

array([ 99, 120])

In [48]:
#scalar multiplication
np.dot(v, w)

219

In [54]:
A = np.array([[0,9,19,13], [1, 20, 5, 13], [12, 11, 3, 4]])
B = np.array([[2,0,0,0], [1,2,2,0], [2,1,1,0], [0,0,1,1]])

C = np.dot(A, B)
C

array([[47, 37, 50, 13],
       [32, 45, 58, 13],
       [41, 25, 29,  4]])

In [55]:
B = np.array([[-1, 33, 4, 1], [0, 1, 1, 0]])

In [56]:
np.mean(B)

4.875

In [59]:
A = np.array([[3,3,3], [1,3,4], [7,1,3]])

In [60]:
np.unique(A)

array([1, 3, 4, 7])